// src/lib/components/Footer.svelte
<script lang="ts">
	import { type Content, isFilled } from '@prismicio/client';
	import { PrismicLink } from '@prismicio/svelte';
	import IconGithub from '~icons/fa-brands/github';

	export let settings: Content.SettingsDocument;
</script>

<footer class="text-slate-600">
	<div
		class="container mx-auto flex mt-20 flex-col items-center justify-between gap-6 py-8 sm:flex-row"
	>
		<div
			class="name flex flex-col items-center justify-center gap-x-4 gap-y-2 sm:flex-row sm:justify-self-start"
		>
			<a
				href="/"
				class="text-xl font-extrabold tracking-tighter text-slate-100 transition-colors duration-150 hover:text-yellow-400"
			>
				{settings.data.name}
			</a>
			<span class="hidden text-5xl font-extralight leading-0 text-slate-400 sm:inline">/</span>
			<p class="text-sm text-slate-300">
				© {new Date().getFullYear()}
				{settings.data.name}
			</p>
		</div>
		<nav class="navigation" aria-label="Footer Navigation">
			<ul class="flex items-center gap-1">
				{#each settings.data.nav_item as { link, label }, index}
					<li>
						<PrismicLink
							field={link}
							class="block px-3 py-1 text-base font-bold text-slate-100 transition-colors duration-150 hover:text-yellow-400"
						>
							{label}
						</PrismicLink>
					</li>
					{#if index < settings.data.nav_item.length - 1}
						<span class="text-4xl font-thin leading-0 text-slate-400 sm:inline" aria-hidden="true"
							>/</span
						>
					{/if}
				{/each}
			</ul>
		</nav>
		<div class="socials inline-flex justify-center sm:justify-end text-slate-100">
			{#if isFilled.link(settings.data.github_link)}
				<PrismicLink
					field={settings.data.github_link}
					class="p-2 text-2xl text-slate-300 transition-all duration-150 hover:scale-125 hover:text-yellow-400"
                    aria-label={settings.data.name + ' on GitHub'}
				>
					<IconGithub />
				</PrismicLink>
			{/if}
            {#if isFilled.link(settings.data.github_link)}
				<PrismicLink
					field={settings.data.github_link}
					class="p-2 text-2xl text-slate-300 transition-all duration-150 hover:scale-125 hover:text-yellow-400"
                    aria-label={settings.data.name + ' on GitHub'}
				>
					<IconGithub />
				</PrismicLink>
			{/if}
		</div>
	</div>
</footer>

// app/components/Footer.tsx
"use client";

import Link from "next/link";
import { ArrowUp } from "lucide-react";
import { site } from "../lib/data";
import { useLang } from "../lib/i18n";

export function Footer() {
  const { content } = useLang();

  return (
    <footer className="relative z-10 border-t border-line">
      <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-5 px-5 py-8 sm:flex-row">
        <p className="text-sm text-muted">
          © {new Date().getFullYear()} {site.name}. {content.footer.rights}
        </p>
        <p className="font-mono text-xs uppercase tracking-[0.2em] text-muted">
          Next.js / Tailwind / Motion
        </p>
        <Link
          href="/"
          aria-label={content.footer.backHome}
          className="group inline-flex h-11 w-11 items-center justify-center rounded-full border border-line bg-white/5 text-ink transition-colors hover:border-accent/60 hover:text-accent"
        >
          <ArrowUp
            size={17}
            aria-hidden="true"
            className="transition-transform duration-300 group-hover:-translate-y-0.5"
          />
        </Link>
      </div>
    </footer>
  );
}
